# Generated by Django 6.0.2 on 2026-02-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sticky Note', 'verbose_name_plural': 'Sticky Notes'},
        ),
    ]
